version: "3"
services:
  php:
    container_name: 'docker_php_1'
    build: ./php
    volumes:
      - ../app:/var/www
    tty: true
    depends_on: 
      - "mysql"

  nginx:
    container_name: 'docker_nginx_1'
    image: nginx:1.21
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ../app:/var/www
    restart: always
    depends_on: 
      - "php"

  mysql:
    container_name: 'docker_mysql_1'
    build: ./mysql
    volumes:
      - ./mysql/dbdata:/var/lib/mysql --user 1000
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-times}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-user!}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root!}
      TZ: "Asia/Tokyo"
    ports:
      - ${MYSQL_PORT:-3306}:3306